name: multi os build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Install GHC and Cabal using ghcup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
        ghcup install ghc 9.4.7
        ghcup set ghc 9.4.7
        ghcup install cabal

    - name: Update Cabal package list
      run: |
        cabal update

    - name: Cache Cabal packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
        key: ${{ runner.os }}-ghc-9.4.7-${{ hashFiles('**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-ghc-9.4.7-

    - name: Build
      run: |
        cabal build --only-dependencies --enable-tests --enable-benchmarks
        cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: |
        cabal test all
